/* Generated by re2c 0.13.7.5 on Sun May 08 21:12:32 2022 */

#include "stdafx.h"

typedef unsigned char uchar;
typedef unsigned int uint;

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr

#define	RET(i)	{s->cur = cursor; return i;}
#define	RETT(i, typeid)	{s->cur = cursor; s->val.type = typeid; return i;}

typedef struct PassData
{
  union {
      int i;
      CString *str;
      COLORREF col;
  };
  uint		type;
} PassData;

typedef struct Scanner
{
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
    PassData val;
} Scanner;

enum {TYPE_CharSet=0, TYPE_AutoDetect, TYPE_ByteOrder, TYPE_FontName, TYPE_FontStyle, TYPE_FontSize, TYPE_FrameLeft, TYPE_FrameTop, TYPE_CmdShow, TYPE_FrameHeight, TYPE_FrameHeight2, TYPE_FrameWidth2, TYPE_SplitHPos, TYPE_SplitVPos, TYPE_SplitStruct, TYPE_StructView, TYPE_ComboHeight, TYPE_Language, TYPE_DetectMax, TYPE_BarState, TYPE_ReadOnly, TYPE_BmpWidth, TYPE_BmpZoom, TYPE_BmpPallet, TYPE_MaxOnMemory, TYPE_MaxMapSize, TYPE_TagAll, TYPE_SubCursor, TYPE_Colors, TYPE_MemberColumns2, TYPE_PageMargin, TYPE_DumpHeader, TYPE_DumpPage, TYPE_QWordAddr, TYPE_ClearUndoRedoWhenSave, TYPE_SyncScroll, TYPE_Grid, TYPE_BmpColorWidth, TYPE_InspectView, TYPE_AnalyzerView, TYPE_BmpAddressTooltip, TYPE_MiniToolbar, TYPE_lastPalletName, TYPE_LastSplitView, TYPE_PortableVersion};

static int g_cfgVer = 0;
static int g_numReadColors = 0;

void SetIntOption(uint type, int val)
{
  switch(type)
  {
case TYPE_CharSet: options.charset = (CharSet)val; break;
case TYPE_AutoDetect: options.bAutoDetect = val; break;
case TYPE_ByteOrder: options.bByteOrder = val; break;
case TYPE_FontStyle: options.fFontStyle = val; break;
case TYPE_FontSize: options.nFontSize = val; break;
case TYPE_FrameLeft: options.ptFrame.x = val; break;
case TYPE_FrameTop: options.ptFrame.y = val; break;
case TYPE_CmdShow: options.nCmdShow = val; break;
case TYPE_FrameHeight: options.cyFrame = val; break;
case TYPE_FrameHeight2: options.cyFrame2 = val; break;
case TYPE_FrameWidth2: options.cxFrame2 = val; break;
case TYPE_SplitHPos: options.xSplit = val; break;
case TYPE_SplitVPos: options.ySplit = val; break;
case TYPE_SplitStruct: options.xSplitStruct = val; break;
case TYPE_StructView: options.bStructView = val; break;
case TYPE_ComboHeight: options.nComboHeight = val; break;
case TYPE_Language: options.bLanguage = val; break;
case TYPE_DetectMax: options.dwDetectMax = val; break;
case TYPE_BarState: options.barState = val; break;
case TYPE_ReadOnly: options.bReadOnlyOpen = val; break;
case TYPE_BmpWidth: options.nBmpWidth = val; break;
case TYPE_BmpZoom: options.nBmpZoom = val; break;
case TYPE_BmpPallet: options.nBmpPallet = val; break;
case TYPE_MaxOnMemory: options.dwMaxOnMemory = val; break;
case TYPE_MaxMapSize: options.dwMaxMapSize = val; break;
case TYPE_TagAll: options.bTagAll = val; break;
case TYPE_SubCursor: options.bSubCursor = val; break;
case TYPE_DumpPage: options.nDumpPage = val; break;
case TYPE_QWordAddr: options.bQWordAddr = val; break;
case TYPE_ClearUndoRedoWhenSave: options.bClearUndoRedoWhenSave = val; break;
case TYPE_SyncScroll: options.bSyncScroll = val; break;
case TYPE_Grid: options.iGrid = val; break;
case TYPE_BmpColorWidth: options.nBmpColorWidth = val; break;
case TYPE_InspectView: options.bInspectView = val; break;
case TYPE_AnalyzerView: options.bAnalyzerView = val; break;
case TYPE_BmpAddressTooltip: options.bAddressTooltip = val; break;
case TYPE_MiniToolbar: options.bMiniToolbar = val; break;
case TYPE_LastSplitView: options.lastSplitView = val; break;
case TYPE_PortableVersion: g_cfgVer = val; break;
	}
}

void SetStrOption(uint type, CString *pVal)
{
  switch(type)
  {
case TYPE_FontName: options.sFontName = *pVal; break;
case TYPE_DumpHeader: options.sDumpHeader = *pVal; break;
case TYPE_lastPalletName: options.lastPalletName = *pVal; break;
	}
}

void SetColorArrOption(uint type, CAtlArray<COLORREF> *pVal)
{
  switch(type)
  {
		case TYPE_Colors:
		{
			COLORREF *col = &(options.colors[0][0]);
			int n = min(TCOLOR_COUNT*2, pVal->GetCount());
			for(int i=0;i < n;i++)
			{
			  col[i] = (*pVal)[i];
			}
			g_numReadColors = max(g_numReadColors, n);
			break;
		}
	}
}

void SetIntArrOption(uint type, CAtlArray<int> *pVal)
{
  switch(type)
  {
		case TYPE_MemberColumns2:
		{
			for(int i=0;i < MBRCOL2_MAX && i < pVal->GetCount();i++)
			{
			  options.colWidth2[i] = (*pVal)[i];
			}
			break;
		}
	}
}

void SetRectOption(uint type, int *pVal)
{
  switch(type)
  {
case TYPE_PageMargin: options.rMargin.left = pVal[0]; options.rMargin.top = pVal[1]; options.rMargin.right = pVal[2]; options.rMargin.bottom = pVal[3]; break;
	}
}

#include "PortableCfgParser.h"
#include "PortableCfgParser.c"


COLORREF ReadRGB(uchar *token)
{
  COLORREF c;
  DWORD r=0, g=0, b=0;
  _snscanf((const char *)token, 6, "%2x%2x%2x", &r, &g, &b);
  c = 0xFF000000 | (r&0xFF) | ((g&0xFF)<<8) | ((b&0xFF)<<16);
  ATLTRACE("ReadRGB: %08X\n", c);
  return c;
}
COLORREF ReadRGBOld(uchar *token)
{
  COLORREF c=0;
  _snscanf((const char *)token, 6, "%x", &c);
  c |= 0xFF000000;
  ATLTRACE("ReadRGBOld: %08X\n", c);
  return c;
}

COLORREF ReadRGBA(uchar *token)
{
  COLORREF c=0;
  DWORD a=0, g=0, b=0;
  _snscanf((const char *)token, 8, "%2x%2x%2x%2x", &c, &g, &b, &a);
  c &= 0xFF;
  c |= ((g&0xFF)<<8) | ((b&0xFF)<<16) | ((a&0xFF)<<24);
  ATLTRACE("ReadRGBA: %08X\n", c);
  return c;
}
COLORREF ReadRGBAOld(uchar *token)
{
  COLORREF c=0;
  _snscanf((const char *)token, 8, "%x", &c);
  ATLTRACE("ReadRGBAOld: %08X\n", c);
  return c;
}

CString ReadStr(uchar *token, uint len)
{
  CStringA tmpA;
  tmpA.SetString((const char *)token, len);
  CStringW tmpB = CA2W(tmpA, CP_UTF8);
  tmpB.Replace(L"%", L"%%");
  CString retStr;
  retStr.Format(tmpB);
  return retStr;
}

BOOL fill(int n) { return FALSE; }

int scan(Scanner *s){
	uchar *cursor = s->cur;
std:
	s->tok = cursor;



{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 21) if(!fill(21)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy20;
	case '\n':	goto yy37;
	case '\v':
	case '\f':	goto yy36;
	case '\r':	goto yy39;
	case 0x1A:	goto yy34;
	case '"':	goto yy25;
	case '#':	goto yy24;
	case '+':
	case '-':	goto yy19;
	case ',':	goto yy32;
	case '/':	goto yy2;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case '=':	goto yy26;
	case 'A':	goto yy6;
	case 'B':	goto yy7;
	case 'C':	goto yy5;
	case 'D':	goto yy11;
	case 'F':	goto yy8;
	case 'G':	goto yy16;
	case 'I':	goto yy17;
	case 'L':	goto yy10;
	case 'M':	goto yy13;
	case 'P':	goto yy4;
	case 'Q':	goto yy15;
	case 'R':	goto yy12;
	case 'S':	goto yy9;
	case 'T':	goto yy14;
	case 'l':	goto yy18;
	case '{':	goto yy28;
	case '}':	goto yy30;
	default:	goto yy40;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy471;
	case '/':	goto yy469;
	default:	goto yy3;
	}
yy3:
	{
    ATLTRACE("unexpected character: %c\n", *s->tok);
    goto std;
  }
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy444;
	case 'o':	goto yy445;
	default:	goto yy3;
	}
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'h':	goto yy396;
	case 'l':	goto yy393;
	case 'm':	goto yy395;
	case 'o':	goto yy394;
	default:	goto yy3;
	}
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy371;
	case 'u':	goto yy372;
	default:	goto yy3;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy309;
	case 'm':	goto yy308;
	case 'y':	goto yy310;
	default:	goto yy3;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy262;
	case 'r':	goto yy261;
	default:	goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'p':	goto yy214;
	case 't':	goto yy213;
	case 'u':	goto yy212;
	case 'y':	goto yy211;
	default:	goto yy3;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy191;
	default:	goto yy3;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy168;
	case 'u':	goto yy167;
	default:	goto yy3;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy159;
	default:	goto yy3;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy117;
	case 'e':	goto yy116;
	case 'i':	goto yy115;
	default:	goto yy3;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy109;
	default:	goto yy3;
	}
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'W':	goto yy100;
	default:	goto yy3;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy96;
	default:	goto yy3;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy85;
	default:	goto yy3;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy71;
	default:	goto yy3;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case ' ':	goto yy69;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy3;
	}
yy20:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy68;
yy21:
	{ if(cursor == s->eof)RET(0); goto std; }
yy22:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy66;
yy23:
	{ uchar *start = s->tok;
				bool bMinus = false;
				if(*start == '-')bMinus = true;
				while(*start<'0' || *start>'9')start++;
				CStringA tmp;
				tmp.SetString((const char *)(start), cursor - start);
				s->val.i = bMinus ? -atoi(tmp) : atoi(tmp);
				RET(INTVAL); }
yy24:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy55;
	default:	goto yy3;
	}
yy25:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy3;
	default:	goto yy45;
	}
yy26:
	++YYCURSOR;
	{ RET(EQ); }
yy28:
	++YYCURSOR;
	{ RET(BR1); }
yy30:
	++YYCURSOR;
	{ RET(BR2); }
yy32:
	++YYCURSOR;
	{ RET(COMMA); }
yy34:
	++YYCURSOR;
	{ RET(0);/*EOF*/ }
yy36:
	yych = *++YYCURSOR;
	goto yy43;
yy37:
	++YYCURSOR;
yy38:
	{
    if(cursor == s->eof)RET(0);
    s->pos = cursor; s->line++;
    goto std;
  }
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy41;
	default:	goto yy38;
	}
yy40:
	yych = *++YYCURSOR;
	goto yy3;
yy41:
	yych = *++YYCURSOR;
	goto yy38;
yy42:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy43:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy42;
	default:	goto yy21;
	}
yy44:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy45:
	switch (yych) {
	case '\n':	goto yy46;
	case '"':	goto yy48;
	case '\\':	goto yy47;
	default:	goto yy44;
	}
yy46:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy3;
	} else {
		goto yy61;
	}
yy47:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy44;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy51;
	case 'x':	goto yy50;
	default:	goto yy46;
	}
yy48:
	++YYCURSOR;
	{ s->val.str = new CString(); *(s->val.str) = ReadStr(s->tok + 1, cursor - s->tok -2); RET(STRVAL); }
yy50:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy53;
	default:	goto yy46;
	}
yy51:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy46;
	case '"':	goto yy48;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy51;
	case '\\':	goto yy47;
	default:	goto yy44;
	}
yy53:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy46;
	case '"':	goto yy48;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy53;
	case '\\':	goto yy47;
	default:	goto yy44;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy56;
	default:	goto yy46;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy57;
	default:	goto yy46;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy58;
	default:	goto yy46;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy59;
	default:	goto yy46;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy60;
	default:	goto yy46;
	}
yy60:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy62;
	default:	goto yy61;
	}
yy61:
	{ s->val.col = ReadRGB(s->tok + 1); RET(COLVAL); }
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy63;
	default:	goto yy46;
	}
yy63:
	++YYCURSOR;
	{ s->val.col = ReadRGBA(s->tok + 1); RET(COLVAL); }
yy65:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy66:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy23;
	}
yy67:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy68:
	switch (yych) {
	case '\t':
	case ' ':	goto yy67;
	case '\v':
	case '\f':	goto yy42;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy21;
	}
yy69:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy69;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy65;
	default:	goto yy46;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy72;
	default:	goto yy46;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy73;
	default:	goto yy46;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy74;
	default:	goto yy46;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy75;
	default:	goto yy46;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy76;
	default:	goto yy46;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy77;
	default:	goto yy46;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy78;
	default:	goto yy46;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy79;
	default:	goto yy46;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy80;
	default:	goto yy46;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy81;
	default:	goto yy46;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy82;
	default:	goto yy46;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy83;
	default:	goto yy46;
	}
yy83:
	++YYCURSOR;
	{ RETT(STRTYPE, TYPE_lastPalletName); }
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy86;
	default:	goto yy46;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy87;
	default:	goto yy46;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy88;
	default:	goto yy46;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy89;
	default:	goto yy46;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy90;
	default:	goto yy46;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy91;
	default:	goto yy46;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy92;
	default:	goto yy46;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy93;
	default:	goto yy46;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy94;
	default:	goto yy46;
	}
yy94:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_InspectView); }
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy97;
	default:	goto yy46;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy98;
	default:	goto yy46;
	}
yy98:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_Grid); }
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy101;
	default:	goto yy46;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy102;
	default:	goto yy46;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy103;
	default:	goto yy46;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy104;
	default:	goto yy46;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy105;
	default:	goto yy46;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy106;
	default:	goto yy46;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy107;
	default:	goto yy46;
	}
yy107:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_QWordAddr); }
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy110;
	default:	goto yy46;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy111;
	default:	goto yy46;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy112;
	default:	goto yy46;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy113;
	default:	goto yy46;
	}
yy113:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_TagAll); }
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy149;
	default:	goto yy46;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy136;
	default:	goto yy46;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy118;
	default:	goto yy46;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy119;
	case 'O':	goto yy120;
	default:	goto yy46;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy129;
	default:	goto yy46;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy121;
	default:	goto yy46;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy122;
	default:	goto yy46;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy123;
	default:	goto yy46;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy124;
	default:	goto yy46;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy125;
	default:	goto yy46;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy126;
	default:	goto yy46;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy127;
	default:	goto yy46;
	}
yy127:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_MaxOnMemory); }
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy130;
	default:	goto yy46;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy131;
	default:	goto yy46;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy132;
	default:	goto yy46;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy133;
	default:	goto yy46;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy134;
	default:	goto yy46;
	}
yy134:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_MaxMapSize); }
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy137;
	default:	goto yy46;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy138;
	default:	goto yy46;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy139;
	default:	goto yy46;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy140;
	default:	goto yy46;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy141;
	default:	goto yy46;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy142;
	default:	goto yy46;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy143;
	default:	goto yy46;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy144;
	default:	goto yy46;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy145;
	default:	goto yy46;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy146;
	default:	goto yy46;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy147;
	default:	goto yy46;
	}
yy147:
	++YYCURSOR;
	{ RETT(INTARRTYPE, TYPE_MemberColumns2); }
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy150;
	default:	goto yy46;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy151;
	default:	goto yy46;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy152;
	default:	goto yy46;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy153;
	default:	goto yy46;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy154;
	default:	goto yy46;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy155;
	default:	goto yy46;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy156;
	default:	goto yy46;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy157;
	default:	goto yy46;
	}
yy157:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_MiniToolbar); }
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy160;
	default:	goto yy46;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy161;
	default:	goto yy46;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy162;
	default:	goto yy46;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy163;
	default:	goto yy46;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy164;
	default:	goto yy46;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy165;
	default:	goto yy46;
	}
yy165:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ReadOnly); }
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy177;
	default:	goto yy46;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy169;
	default:	goto yy46;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy170;
	default:	goto yy46;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy171;
	default:	goto yy46;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy172;
	default:	goto yy46;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy173;
	default:	goto yy46;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy174;
	default:	goto yy46;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy175;
	default:	goto yy46;
	}
yy175:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_DetectMax); }
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy178;
	default:	goto yy46;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy179;
	case 'P':	goto yy180;
	default:	goto yy46;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy185;
	default:	goto yy46;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy181;
	default:	goto yy46;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy182;
	default:	goto yy46;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy183;
	default:	goto yy46;
	}
yy183:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_DumpPage); }
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy186;
	default:	goto yy46;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy187;
	default:	goto yy46;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy46;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy189;
	default:	goto yy46;
	}
yy189:
	++YYCURSOR;
	{ RETT(STRTYPE, TYPE_DumpHeader); }
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy192;
	case 's':	goto yy193;
	default:	goto yy46;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy205;
	default:	goto yy46;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy194;
	default:	goto yy46;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy195;
	default:	goto yy46;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy196;
	default:	goto yy46;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy197;
	default:	goto yy46;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy198;
	default:	goto yy46;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy199;
	default:	goto yy46;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy200;
	default:	goto yy46;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy201;
	default:	goto yy46;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy202;
	default:	goto yy46;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy203;
	default:	goto yy46;
	}
yy203:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_LastSplitView); }
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy206;
	default:	goto yy46;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy207;
	default:	goto yy46;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy208;
	default:	goto yy46;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy209;
	default:	goto yy46;
	}
yy209:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_Language); }
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy252;
	default:	goto yy46;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy244;
	default:	goto yy46;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy235;
	default:	goto yy46;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy215;
	default:	goto yy46;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy216;
	default:	goto yy46;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy217;
	default:	goto yy46;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy220;
	case 'S':	goto yy218;
	case 'V':	goto yy219;
	default:	goto yy46;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy229;
	default:	goto yy46;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy225;
	default:	goto yy46;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy221;
	default:	goto yy46;
	}
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy222;
	default:	goto yy46;
	}
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy223;
	default:	goto yy46;
	}
yy223:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitHPos); }
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy226;
	default:	goto yy46;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy227;
	default:	goto yy46;
	}
yy227:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitVPos); }
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy230;
	default:	goto yy46;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy231;
	default:	goto yy46;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy232;
	default:	goto yy46;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy233;
	default:	goto yy46;
	}
yy233:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitStruct); }
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy236;
	default:	goto yy46;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy237;
	default:	goto yy46;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy238;
	default:	goto yy46;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy239;
	default:	goto yy46;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy240;
	default:	goto yy46;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy241;
	default:	goto yy46;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy242;
	default:	goto yy46;
	}
yy242:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_StructView); }
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy245;
	default:	goto yy46;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy246;
	default:	goto yy46;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy247;
	default:	goto yy46;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy248;
	default:	goto yy46;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy249;
	default:	goto yy46;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy250;
	default:	goto yy46;
	}
yy250:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SubCursor); }
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy253;
	default:	goto yy46;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy254;
	default:	goto yy46;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy255;
	default:	goto yy46;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy256;
	default:	goto yy46;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy257;
	default:	goto yy46;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy258;
	default:	goto yy46;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy259;
	default:	goto yy46;
	}
yy259:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SyncScroll); }
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy280;
	default:	goto yy46;
	}
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy263;
	default:	goto yy46;
	}
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy264;
	default:	goto yy46;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy265;
	case 'S':	goto yy266;
	default:	goto yy46;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy276;
	default:	goto yy46;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy267;
	case 't':	goto yy268;
	default:	goto yy46;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy273;
	default:	goto yy46;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy269;
	default:	goto yy46;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy270;
	default:	goto yy46;
	}
yy270:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy271;
	default:	goto yy46;
	}
yy271:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FontStyle); }
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy274;
	default:	goto yy46;
	}
yy274:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FontSize); }
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy277;
	default:	goto yy46;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy278;
	default:	goto yy46;
	}
yy278:
	++YYCURSOR;
	{ RETT(STRTYPE, TYPE_FontName); }
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy281;
	default:	goto yy46;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy282;
	default:	goto yy46;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy284;
	case 'L':	goto yy286;
	case 'T':	goto yy285;
	case 'W':	goto yy283;
	default:	goto yy46;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy302;
	default:	goto yy46;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy294;
	default:	goto yy46;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy291;
	default:	goto yy46;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy287;
	default:	goto yy46;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy288;
	default:	goto yy46;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy289;
	default:	goto yy46;
	}
yy289:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameLeft); }
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy292;
	default:	goto yy46;
	}
yy292:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameTop); }
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy295;
	default:	goto yy46;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy296;
	default:	goto yy46;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy297;
	default:	goto yy46;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy298;
	default:	goto yy46;
	}
yy298:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '2':	goto yy300;
	default:	goto yy299;
	}
yy299:
	{ RETT(INTTYPE, TYPE_FrameHeight); }
yy300:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameHeight2); }
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy303;
	default:	goto yy46;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy304;
	default:	goto yy46;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy305;
	default:	goto yy46;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy306;
	default:	goto yy46;
	}
yy306:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameWidth2); }
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy326;
	default:	goto yy46;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy319;
	default:	goto yy46;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy311;
	default:	goto yy46;
	}
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy312;
	default:	goto yy46;
	}
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy313;
	default:	goto yy46;
	}
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy314;
	default:	goto yy46;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy315;
	default:	goto yy46;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy316;
	default:	goto yy46;
	}
yy316:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy317;
	default:	goto yy46;
	}
yy317:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ByteOrder); }
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy320;
	default:	goto yy46;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy321;
	default:	goto yy46;
	}
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy322;
	default:	goto yy46;
	}
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy323;
	default:	goto yy46;
	}
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy324;
	default:	goto yy46;
	}
yy324:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BarState); }
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy327;
	case 'C':	goto yy328;
	case 'P':	goto yy329;
	case 'W':	goto yy331;
	case 'Z':	goto yy330;
	default:	goto yy46;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy357;
	default:	goto yy46;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy347;
	default:	goto yy46;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy341;
	default:	goto yy46;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy337;
	default:	goto yy46;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy332;
	default:	goto yy46;
	}
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy333;
	default:	goto yy46;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy334;
	default:	goto yy46;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy335;
	default:	goto yy46;
	}
yy335:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpWidth); }
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy338;
	default:	goto yy46;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy339;
	default:	goto yy46;
	}
yy339:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpZoom); }
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy342;
	default:	goto yy46;
	}
yy342:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy343;
	default:	goto yy46;
	}
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy344;
	default:	goto yy46;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy345;
	default:	goto yy46;
	}
yy345:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpPallet); }
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy348;
	default:	goto yy46;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy349;
	default:	goto yy46;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy350;
	default:	goto yy46;
	}
yy350:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':	goto yy351;
	default:	goto yy46;
	}
yy351:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy352;
	default:	goto yy46;
	}
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy353;
	default:	goto yy46;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy354;
	default:	goto yy46;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy355;
	default:	goto yy46;
	}
yy355:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpColorWidth); }
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy358;
	default:	goto yy46;
	}
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy359;
	default:	goto yy46;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy360;
	default:	goto yy46;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy361;
	default:	goto yy46;
	}
yy361:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy362;
	default:	goto yy46;
	}
yy362:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy363;
	default:	goto yy46;
	}
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy364;
	default:	goto yy46;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy365;
	default:	goto yy46;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy366;
	default:	goto yy46;
	}
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy367;
	default:	goto yy46;
	}
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy368;
	default:	goto yy46;
	}
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy369;
	default:	goto yy46;
	}
yy369:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpAddressTooltip); }
yy371:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy382;
	default:	goto yy46;
	}
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy373;
	default:	goto yy46;
	}
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy374;
	default:	goto yy46;
	}
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy375;
	default:	goto yy46;
	}
yy375:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy376;
	default:	goto yy46;
	}
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy377;
	default:	goto yy46;
	}
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy378;
	default:	goto yy46;
	}
yy378:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy379;
	default:	goto yy46;
	}
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy380;
	default:	goto yy46;
	}
yy380:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_AutoDetect); }
yy382:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy383;
	default:	goto yy46;
	}
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy384;
	default:	goto yy46;
	}
yy384:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy385;
	default:	goto yy46;
	}
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy386;
	default:	goto yy46;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy387;
	default:	goto yy46;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy388;
	default:	goto yy46;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy389;
	default:	goto yy46;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy390;
	default:	goto yy46;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy391;
	default:	goto yy46;
	}
yy391:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_AnalyzerView); }
yy393:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy424;
	default:	goto yy46;
	}
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy410;
	case 'm':	goto yy409;
	default:	goto yy46;
	}
yy395:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy403;
	default:	goto yy46;
	}
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy397;
	default:	goto yy46;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy398;
	default:	goto yy46;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy399;
	default:	goto yy46;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy400;
	default:	goto yy46;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy401;
	default:	goto yy46;
	}
yy401:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_CharSet); }
yy403:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy404;
	default:	goto yy46;
	}
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy405;
	default:	goto yy46;
	}
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy406;
	default:	goto yy46;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy407;
	default:	goto yy46;
	}
yy407:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_CmdShow); }
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy415;
	default:	goto yy46;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy411;
	default:	goto yy46;
	}
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy412;
	default:	goto yy46;
	}
yy412:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy413;
	default:	goto yy46;
	}
yy413:
	++YYCURSOR;
	{ RETT(COLORARRTYPE, TYPE_Colors); }
yy415:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy416;
	default:	goto yy46;
	}
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy417;
	default:	goto yy46;
	}
yy417:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy418;
	default:	goto yy46;
	}
yy418:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy419;
	default:	goto yy46;
	}
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy420;
	default:	goto yy46;
	}
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy421;
	default:	goto yy46;
	}
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy422;
	default:	goto yy46;
	}
yy422:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ComboHeight); }
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy425;
	default:	goto yy46;
	}
yy425:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy426;
	default:	goto yy46;
	}
yy426:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':	goto yy427;
	default:	goto yy46;
	}
yy427:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy428;
	default:	goto yy46;
	}
yy428:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy429;
	default:	goto yy46;
	}
yy429:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy430;
	default:	goto yy46;
	}
yy430:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':	goto yy431;
	default:	goto yy46;
	}
yy431:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy432;
	default:	goto yy46;
	}
yy432:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy433;
	default:	goto yy46;
	}
yy433:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy434;
	default:	goto yy46;
	}
yy434:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':	goto yy435;
	default:	goto yy46;
	}
yy435:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy436;
	default:	goto yy46;
	}
yy436:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy437;
	default:	goto yy46;
	}
yy437:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy438;
	default:	goto yy46;
	}
yy438:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy439;
	default:	goto yy46;
	}
yy439:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy440;
	default:	goto yy46;
	}
yy440:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy441;
	default:	goto yy46;
	}
yy441:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy442;
	default:	goto yy46;
	}
yy442:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ClearUndoRedoWhenSave); }
yy444:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy460;
	default:	goto yy46;
	}
yy445:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy446;
	default:	goto yy46;
	}
yy446:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy447;
	default:	goto yy46;
	}
yy447:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy448;
	default:	goto yy46;
	}
yy448:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy449;
	default:	goto yy46;
	}
yy449:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy450;
	default:	goto yy46;
	}
yy450:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy451;
	default:	goto yy46;
	}
yy451:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy452;
	default:	goto yy46;
	}
yy452:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy453;
	default:	goto yy46;
	}
yy453:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy454;
	default:	goto yy46;
	}
yy454:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy455;
	default:	goto yy46;
	}
yy455:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy456;
	default:	goto yy46;
	}
yy456:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy457;
	default:	goto yy46;
	}
yy457:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy458;
	default:	goto yy46;
	}
yy458:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_PortableVersion); }
yy460:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy461;
	default:	goto yy46;
	}
yy461:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy462;
	default:	goto yy46;
	}
yy462:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy463;
	default:	goto yy46;
	}
yy463:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy464;
	default:	goto yy46;
	}
yy464:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy465;
	default:	goto yy46;
	}
yy465:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy466;
	default:	goto yy46;
	}
yy466:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy467;
	default:	goto yy46;
	}
yy467:
	++YYCURSOR;
	{ RETT(RECTTYPE, TYPE_PageMargin); }
yy469:
	++YYCURSOR;
	{ goto comment2; }
yy471:
	++YYCURSOR;
	{ goto comment; }
}


comment:

{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) if(!fill(2)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy477;
	case '*':	goto yy475;
	default:	goto yy479;
	}
yy475:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy480;
	default:	goto yy476;
	}
yy476:
	{ if(cursor == s->eof)RET(0); goto comment; }
yy477:
	++YYCURSOR;
	{ if(cursor == s->eof) RET(0); s->tok = s->pos = cursor; s->line++; goto comment; }
yy479:
	yych = *++YYCURSOR;
	goto yy476;
yy480:
	++YYCURSOR;
	{ if(cursor == s->eof || cursor+1 == s->eof)RET(0); goto std; }
}

comment2:

{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy484;
	default:	goto yy486;
	}
yy484:
	++YYCURSOR;
	{ if(cursor == s->eof) RET(0); s->tok = s->pos = cursor; s->line++; goto std; }
yy486:
	++YYCURSOR;
	{ if(cursor == s->eof)RET(0); goto comment2; }
}

}